// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa25VVBfm7vakobydRveMGlAaXmKXJOHo',
    appId: '1:1070565225371:web:ac409b1e64623eb493273e',
    messagingSenderId: '1070565225371',
    projectId: 'family-link-9747e',
    authDomain: 'family-link-9747e.firebaseapp.com',
    storageBucket: 'family-link-9747e.firebasestorage.app',
    measurementId: 'G-VF171M9HQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfjEDYeVjG02mnQLrJ-HIhyLn6-o7Y-Sc',
    appId: '1:1070565225371:android:07fdca02a4f4e23793273e',
    messagingSenderId: '1070565225371',
    projectId: 'family-link-9747e',
    storageBucket: 'family-link-9747e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGSb5lNmJPPseb2Hi8ZP1-tX4osdwMkH8',
    appId: '1:1070565225371:ios:0e0780f48a74e94893273e',
    messagingSenderId: '1070565225371',
    projectId: 'family-link-9747e',
    storageBucket: 'family-link-9747e.firebasestorage.app',
    iosBundleId: 'com.example.familyLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGSb5lNmJPPseb2Hi8ZP1-tX4osdwMkH8',
    appId: '1:1070565225371:ios:0e0780f48a74e94893273e',
    messagingSenderId: '1070565225371',
    projectId: 'family-link-9747e',
    storageBucket: 'family-link-9747e.firebasestorage.app',
    iosBundleId: 'com.example.familyLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa25VVBfm7vakobydRveMGlAaXmKXJOHo',
    appId: '1:1070565225371:web:2585018fc4d871b693273e',
    messagingSenderId: '1070565225371',
    projectId: 'family-link-9747e',
    authDomain: 'family-link-9747e.firebaseapp.com',
    storageBucket: 'family-link-9747e.firebasestorage.app',
    measurementId: 'G-EXEHJZPK2D',
  );
}
